apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo-database
  namespace: preview
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:14.12-v0.3.0
  enableSuperuserAccess: true
  bootstrap:
    recovery:
      backup:
        name: demo-database-snapshot
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  storage:
    size: 10Gi
    storageClass: zfs
  backup:
    volumeSnapshot:
      className: zfs
