kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-library
  namespace: preview
spec:
  dataSource:
    name: preview-base-library-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: zfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
