apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vmetrics-read-token
  namespace: monitoring-dev
spec:
  itemPath: "vaults/Kubernetes/items/vmetrics_read_token"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: read
  namespace: monitoring-dev
spec:
  tokenRef:
    name: vmetrics-read-token
    key: token
  targetRefs:
    - crd:
        kind: VMSingle
        name: vmetrics-dev
        namespace: monitoring-dev
      paths: ["/api/v1/query","/api/v1/query_range","/api/v1/series","/api/v1/labels"]
