apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: cf-workers
  namespace: monitoring-dev
spec:
  tokenRef:
    name: cf-workers-metrics-token
    key: token
  targetRefs:
    - crd:
        kind: VMSingle
        name: vmetrics-dev
        namespace: monitoring-dev
      paths: ["/write"]
