---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cloudnative-pg/ks.yaml
  - ./grafana-operator/ks.yaml
  - ./flux-operator/ks.yaml
  - ./victoria-metrics/ks.yaml
