---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-dev-volsync-repo
  namespace: outline-dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-tf
  refreshInterval: "20s"
  target:
    template:
      engineVersion: v2
      data:
        RESTIC_PASSWORD: "{{ .restic_password }}"
        RESTIC_REPOSITORY: "s3:{{ .endpoint }}/{{ .bucket_name }}"
        AWS_ACCESS_KEY_ID: "{{ .access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_access_key }}"
  data:
    - secretKey: restic_password
      remoteRef:
        key: OUTLINE_VOLSYNC_BACKUPS_RESTIC_SECRET
    - secretKey: access_key_id
      remoteRef:
        key: OUTLINE_VOLSYNC_BACKUPS_BUCKET
        property: access_key_id
    - secretKey: secret_access_key
      remoteRef:
        key: OUTLINE_VOLSYNC_BACKUPS_BUCKET
        property: secret_access_key
    - secretKey: bucket_name
      remoteRef:
        key: OUTLINE_VOLSYNC_BACKUPS_BUCKET
        property: bucket_name
    - secretKey: endpoint
      remoteRef:
        key: OUTLINE_VOLSYNC_BACKUPS_BUCKET
        property: endpoint
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: outline-dev-bootstrap
  namespace: outline-dev
spec:
  trigger:
    manual: restore-once
  restic:
    copyMethod: Snapshot
    repository: outline-dev-volsync-repo
    cacheStorageClassName: zfs
    cacheCapacity: 1Gi
    storageClassName: zfs
    volumeSnapshotClassName: zfs
    accessModes:
      - ReadWriteOnce
    capacity: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-dev
  namespace: outline-dev
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: outline-dev-bootstrap
  resources:
    requests:
      storage: 20Gi
  storageClassName: zfs
