apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-master-key
  namespace: authentication
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-tf
  refreshInterval: "20s"
  data:
    - secretKey: masterkey
      remoteRef:
        key: AUTH_ZITADEL_MASTER_KEY
