apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-controller
  namespace: preview
spec:
  schedule: "0 */5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: demo-controller
          containers:
            - name: demo-controller
              image: ghcr.io/fluxcd/flux-cli:v2.9.0@sha256:67ef7f17069e3898551fe3c0f145fb8ce9ace2fcb6320b1f57f89a7a82204600
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  #!/bin/bash

                  set -o errexit
                  set -o nounset

                  kubectl scale --replicas=0 --namespace=preview deployment/demo-server

                  kubectl rollout restart --namespace=preview deployment/demo-valkey
                  kubectl delete cluster demo-database --wait=true --cascade=foreground --namespace=preview
                  flux reconcile kustomization demo-deployment --namespace=flux-system

                  kubectl scale --replicas=1 --namespace=preview deployment/demo-server
          restartPolicy: OnFailure
