apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-controller
  namespace: preview
spec:
  schedule: "0 */5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: demo-controller
          containers:
            - name: demo-controller
              image: ghcr.io/fluxcd/flux-cli:v2.8.3@sha256:1fe5c39881c0c1f857f0462f0692e365bea768228b33d31c209610f389775eb6
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  #!/bin/bash

                  set -o errexit
                  set -o nounset

                  kubectl scale --replicas=0 --namespace=preview deployment/demo-server

                  kubectl rollout restart --namespace=preview deployment/demo-valkey
                  kubectl delete cluster demo-database --wait=true --cascade=foreground --namespace=preview
                  flux reconcile kustomization demo-deployment --namespace=flux-system

                  kubectl scale --replicas=1 --namespace=preview deployment/demo-server
          restartPolicy: OnFailure
