apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-controller
  namespace: preview
spec:
  schedule: "0 */5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: demo-controller
          containers:
            - name: demo-controller
              image: ghcr.io/fluxcd/flux-cli:v2.9.3@sha256:148ad45c3bd6e2f051bda3d1e4572a1f4e546b3fc0b658bf1391ac1ec277a475
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  #!/bin/bash

                  set -o errexit
                  set -o nounset

                  kubectl scale --replicas=0 --namespace=preview deployment/demo-server

                  kubectl rollout restart --namespace=preview deployment/demo-valkey
                  kubectl delete cluster demo-database --wait=true --cascade=foreground --namespace=preview
                  flux reconcile kustomization demo-deployment --namespace=flux-system

                  kubectl scale --replicas=1 --namespace=preview deployment/demo-server
          restartPolicy: OnFailure
