apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-controller
  namespace: preview
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-controller
rules:
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    resourceNames: ["demo-deployment"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    resourceNames: ["demo-deployment-parent"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: demo-controller
subjects:
  - kind: ServiceAccount
    name: demo-controller
    namespace: preview
