apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-controller
  namespace: preview
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # TODO: Should this just be a Role?
metadata:
  name: demo-controller
rules:
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    resourceNames: ["demo-deployment"]
    verbs: ["get", "list", "delete", "watch"]
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["clusters"]
    resourceNames: ["demo-database"]
    verbs: ["get", "list", "delete", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    resourceNames: ["demo-server"]
    verbs: ["get", "list", "delete", "watch", "patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    resourceNames: ["demo-redis-master"]
    verbs: ["get", "list", "delete", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: demo-controller
subjects:
  - kind: ServiceAccount
    name: demo-controller
    namespace: preview
