apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metrics-admin-token
  namespace: monitoring-dev
spec:
  secretStoreRef:
    name: tf-dev
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: METRICS_ADMIN_TOKEN
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: metrics-admin
  namespace: monitoring-dev
  labels:
    vm-user: "admin"
spec:
  tokenRef:
    name: metrics-admin-token
    key: token
  targetRefs:
    - crd:
        kind: VMSingle
        name: vmetrics-dev
        namespace: monitoring-dev
      paths: ["/api/v1/admin.*"]
