apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: immich-github-previews
  namespace: preview
spec:
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: immich-github-prs
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: immich-github-branches
  inputs:
    - branch: release
      # renovate: datasource=github-releases depName=immich-app/immich
      tag: "v1.137.3"
  resourcesTemplate: |
    <<- $ctx := dict >>
    <<- if hasKey inputs "author" >>
      <<- $name := list "pr" inputs.id | join "-" >>
      <<- $_ := set $ctx "name" $name >>
    <<- else >>
      <<- $_ := set $ctx "name" inputs.branch >>
    <<- end >>

    <<- if hasKey inputs "sha" >>
      <<- $tag := list "commit" inputs.sha | join "-" >>
      <<- $_ := set $ctx "tag" $tag >>
    <<- else >>
      <<- $_ := set $ctx "tag" inputs.tag >>
    <<- end >>
    
    ---
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: << $ctx.name >>-preview-database
      namespace: preview
    spec:
      instances: 1
      imageName: ghcr.io/tensorchord/cloudnative-vectorchord:14.18-0.3.0
      enableSuperuserAccess: true
      bootstrap:
        recovery:
          backup:
            name: preview-base-database-snapshot
      postgresql:
        shared_preload_libraries:
          - "vchord.so"
      storage:
        size: 10Gi
        storageClass: zfs
      backup:
        volumeSnapshot:
          className: zfs
    ---
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: << $ctx.name >>-preview-library
      namespace: preview
    spec:
      dataSource:
        name: preview-base-library-snapshot
        kind: VolumeSnapshot
        apiGroup: snapshot.storage.k8s.io
      storageClassName: zfs
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
    ---
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: << $ctx.name >>-preview
      namespace: preview
    spec:
      interval: 5m
      timeout: 20m
      install:
        disableWait: true
      upgrade:
        disableWait: true
      chart:
        spec:
          chart: immich
          # renovate: datasource=github-releases depName=immich-app/immich-charts
          version: "0.9.3"
          sourceRef:
            kind: HelmRepository
            name: immich-charts
            namespace: flux-system
          interval: 1m
      values:
        postgres:
          enabled: false
        redis:
          enabled: true
        immich:
          persistence:
            library:
              existingClaim: << $ctx.name >>-preview-library
        env:
          DB_HOSTNAME:
            valueFrom:
              secretKeyRef:
                name: << $ctx.name >>-preview-database-superuser
                key: host
          DB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: << $ctx.name >>-preview-database-superuser
                key: user
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: << $ctx.name >>-preview-database-superuser
                key: password
          DB_DATABASE_NAME:
            valueFrom:
              secretKeyRef:
                name: << $ctx.name >>-preview-database-app
                key: dbname
          LOG_LEVEL: verbose
        image:
          tag: << $ctx.tag >>
        server:
          image:
            pullPolicy: Always
          ingress:
            main:
              enabled: true
              className: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-production
                nginx.ingress.kubernetes.io/proxy-body-size: "0"
              hosts:
                - host: << $ctx.name >>.preview.internal.immich.cloud
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - hosts:
                    - << $ctx.name >>.preview.internal.immich.cloud
                  secretName: << $ctx.name >>-preview-tls
        machine-learning:
          image:
            pullPolicy: Always

