---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
  namespace: authentication
spec:
  interval: 5m
  chart:
    spec:
      chart: dex
      version: 0.19.1
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/dexidp/dex
      tag: v2.41.1@sha256:bc7cfce7c17f52864e2bb2a4dc1d2f86a41e3019f6d42e81d92a301fad0c8a1d
    env:
      KUBERNETES_POD_NAMESPACE: authentication
    envFrom:
      - secretRef:
          name: github-oauth-client
      - secretRef:
          name: hedgedoc-oauth
      - secretRef:
          name: grafana-oauth
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: &host auth.immich.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: dex-tls

    config:
      issuer: &issuer https://auth.immich.cloud

      storage:
        type: kubernetes
        config:
          inCluster: true

      web:
        http: 0.0.0.0:5556

      frontend:
        issuer: immich
        issuerUrl: *issuer
        logoUrl: https://github.com/immich-app/immich/raw/main/design/immich-logo-no-outline.png

      expiry:
        signingKeys: "6h"
        idTokens: "24h"

      logger:
        level: debug
        format: text

      oauth2:
        responseTypes: ["code", "token", "id_token"]
        skipApprovalScreen: true
        alwaysShowLoginScreen: false

      enablePasswordDB: false

      connectors:
        # GitHub configure 'OAuth Apps' -> 'New OAuth App', add callback URL
        # https://github.com/settings/developers
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $GITHUB_CLIENT_ID
            clientSecret: $GITHUB_CLIENT_SECRET
            redirectURI: https://auth.immich.cloud/callback
            orgs:
              - name: immich-app

      staticClients:
        - id: hedgedoc
          name: hedgedoc
          secretEnv: CMD_OAUTH2_CLIENT_SECRET
          redirectURIs:
            - "https://md.immich.cloud/auth/oauth2/callback"
        - id: containerssh
          name: containerssh
          public: true
          redirectURIs:
            - "/device/callback"
        - id: grafana
          name: grafana
          secretEnv: GRAFANA_OAUTH_CLIENT_SECRET
          redirectURIs:
            - "https://monitoring.immich.cloud/login/generic_oauth"
            - "https://monitoring.dev.immich.cloud/login/generic_oauth"

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
