apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: github-oauth-client
  namespace: authentication
spec:
  itemPath: "vaults/Kubernetes/items/github-oauth-client"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: hedgedoc-oauth
  namespace: authentication
spec:
  itemPath: "vaults/Kubernetes/items/hedgedoc-oauth"
