apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich-charts
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/immich-app/immich-charts/immich
  ref:
    tag: "0.12.1"
