---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: terraform-state-storage-secrets
  namespace: flux-system
spec:
  path: ./kubernetes/apps/infrastructure/terraform/state-storage/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  dependsOn:
    - name: cluster-apps-onepassword
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: terraform-state-storage
  namespace: flux-system
spec:
  path: ./kubernetes/apps/infrastructure/terraform/state-storage/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  dependsOn:
    - name: database-cloudnative-pg
    - name: terraform-state-storage-secrets
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: tf-state-backup-bucket
