apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metrics-write-token
  namespace: monitoring
spec:
  secretStoreRef:
    name: 1p-tf-prod
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: METRICS_WRITE_TOKEN
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: metrics-write
  namespace: monitoring
  labels:
    vm-user: "write"
spec:
  tokenRef:
    name: metrics-write-token
    key: token
  targetRefs:
    - crd:
        kind: VMSingle
        name: vmetrics
        namespace: monitoring
      paths: ["/write"]
