apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app outline-secrets
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
    - name: zitadel
  path: ./kubernetes/apps/tools/outline/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app outline
  namespace: flux-system
spec:
  targetNamespace: tools
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: outline-secrets
  path: ./kubernetes/apps/tools/outline/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: outline-database-backup-bucket
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 20Gi
      VOLSYNC_SCHEDULE: "0 17 * * *"
      VOLSYNC_SECRET_STORE: 1p-tf
      VOLSYNC_RESTIC_PASSWORD_SECRET: OUTLINE_VOLSYNC_BACKUPS_RESTIC_SECRET
      VOLSYNC_BUCKET_SECRET: OUTLINE_VOLSYNC_BACKUPS_BUCKET
