---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.30.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: vmetrics
    defaultDashboards:
      grafanaOperator:
        enabled: true
    alertmanager:
      enabled: false
    vmalert:
      enabled: false
    grafana:
      enabled: false
    kubeEtcd:
      enabled: false
    vmsingle:
      spec:
        extraArgs:
          search.maxUniqueTimeseries: "600000"
        resources: {}
    vmagent:
      spec:
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
