apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-metrics
  namespace: monitoring-dev
spec:
  uid: '36979063-5384-4eb9-8679-565a727cbc13'
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: victoria-metrics
    type: prometheus
    access: proxy
    url: http://vmsingle-vmetrics-dev:8429
    isDefault: true
