apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-metrics
  namespace: monitoring-dev
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: victoria-metrics
    type: prometheus
    access: proxy
    url: http://vmsingle-vmetrics:8429
    isDefault: true
