apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: demo-library-snapshot
  namespace: preview
spec:
  volumeSnapshotClassName: zfs
  source:
    persistentVolumeClaimName: pr-17357-preview-library
