# permissions for end users to edit previews.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: preview-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: preview-operator
    app.kubernetes.io/part-of: preview-operator
    app.kubernetes.io/managed-by: kustomize
  name: preview-editor-role
rules:
- apiGroups:
  - devtools.immich.app
  resources:
  - previews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devtools.immich.app
  resources:
  - previews/status
  verbs:
  - get
