---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: registry
  namespace: preview
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: registry
              tag: 2.8.3
            env:
              REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
              # Default TTL is 7 days
              REGISTRY_DELETE_ENABLED: "true"
    service:
      main:
        ports:
          http:
            port: 5000
    persistence:
      data:
        enabled: true
        storageClass: zfs
        size: 100Gi
        accessMode: ReadWriteOnce
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: registry-auth
        hosts:
          - host: &host preview-registry.internal.immich.cloud
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: preview-registry-tls
