apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-metrics
  namespace: monitoring
spec:
  uid: '36979063-5384-4eb9-8679-565a727cbc13'
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: victoria-metrics
    type: prometheus
    access: proxy
    url: http://vmsingle-vmetrics:8428
    isDefault: true
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-logs
  namespace: monitoring
spec:
  uid: 'ccbc6262-66f9-11f0-aaad-c3ab79336d7c'
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: victoria-logs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victoria-logs-victoria-logs-single-server:9428
  plugins:
    - name: victoriametrics-logs-datasource
      version: 0.18.1
