apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: "grafana"
spec:
  # TODO: Oauth login
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
  deployment:
    spec:
      template:
        spec:
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
  ingress:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
    spec:
      ingressClassName: nginx
      rules:
        - host: &host monitoring.immich.cloud
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: grafana-tls-secret
