---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-image-renderer
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/grafana/grafana-image-renderer
              tag: v5.8.0@sha256:0f61a5e8d0e22fbe96173701185e93235fef30567f3b35a80a0ceda82737c874
    service:
      main:
        controller: main
        ports:
          http:
            port: 8081
