---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-image-renderer
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/grafana/grafana-image-renderer
              tag: v5.8.1@sha256:1f2b6832d06b4dda84267b712f51b91d20d7a3fdfca4239f042f86e100948a5c
    service:
      main:
        controller: main
        ports:
          http:
            port: 8081
