apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app monitoring-ingress
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: victoria-metrics
  path: ./kubernetes/apps/monitoring/ingress/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
