apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: preview-base-database-snapshot
  namespace: preview
spec:
  cluster:
    name: temp-snapshot-base
  method: volumeSnapshot
  online: false
