apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: preview-base-library-snapshot
  namespace: preview
spec:
  volumeSnapshotClassName: zfs
  source:
    persistentVolumeClaimName: temp-snapshot-base-library
