---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-cache
  namespace: actions-cache
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/falcondev-oss/github-actions-cache-server
              tag: 8.1.2@sha256:ae13d4e5aeb25bcef3591cde5e2f73a8effa2d61fbb94550954a58b4370113ea
            env:
              API_BASE_URL: "http://actions-cache.actions-cache.svc.cluster.local:3000"
              STORAGE_FILESYSTEM_PATH: "/data/cache"
              DB_SQLITE_PATH: "/data/sqlite.db"
    service:
      main:
        ports:
          http:
            port: 3000
    persistence:
      data:
        enabled: true
        storageClass: zfs
        size: 100Gi
        accessMode: ReadWriteOnce
