name: 'Success check'
description: 'Check for successful run of a matrix job'
inputs:
  needs:
    description: 'The needs context with the matrix job results'
    required: true
runs:
  using: 'composite'
  steps: # TODO: check each condition much more explicitly
    - name: Any jobs failed?
      if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
      shell: bash
      run: exit 1
    - name: All jobs passed or skipped
      if: ${{ !(contains(needs.*.result, 'failure')) && !contains(needs.*.result, 'cancelled') }}
      shell: bash
      # zizmor: ignore[template-injection]
      run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
