name: 'Success check'
description: 'Check for successful run of a matrix job'
inputs:
  needs:
    description: 'The needs context with the matrix job results'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Success check
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        INPUT: ${{ inputs.needs }}
      with:
        script: |
          const needs = JSON.parse(process.env.INPUT);
          const results = Object.values(needs).map(job => job.result);
          console.log(`Job results: ${results}`);
          if (results.includes('failure') || results.includes('cancelled')) {
            throw new Error('One or more jobs failed or were cancelled');
          } else if (results.every(result => result === 'success' || result === 'skipped')) {
            console.log('All jobs passed or were skipped');
            return;
          } else {
            throw new Error('Unexpected job results');
          }
