---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-controller
---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-runners
---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-cache
