---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  path: ./kubernetes/apps/infrastructure/secrets/external-secrets/app
  prune: true
  dependsOn:
    - name: cluster-apps-onepassword
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: external-secrets
      namespace: secrets
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: flux-system
spec:
  path: ./kubernetes/apps/infrastructure/secrets/external-secrets/stores
  prune: true
  dependsOn:
    - name: external-secrets
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
