apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: outline-database-backup-secret
  namespace: tools
  labels:
    cnpg.io/reload: true
spec:
  itemPath: "vaults/Kubernetes/items/mich-cloudflare-r2-token"
