apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-oauth-client
  namespace: tools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-tf
  refreshInterval: "20s"
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: ZITADEL_OAUTH_CLIENT_ID_OUTLINE
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: ZITADEL_OAUTH_CLIENT_SECRET_OUTLINE
