apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app1 victoria-logs
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app1
  dependsOn:
    - name: grafana-operator
    - name: victoria-metrics-operator
  path: ./kubernetes/apps/monitoring/victoria-logs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: victoria-logs
      VOLSYNC_CAPACITY: 100Gi
      VOLSYNC_SECRET_STORE: 1p-tf
      VOLSYNC_RESTIC_PASSWORD_SECRET: VICTORIALOGS_VOLSYNC_BACKUPS_RESTIC_SECRET
      VOLSYNC_BUCKET_SECRET: VICTORIALOGS_VOLSYNC_BACKUPS_BUCKET
