apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: geocoding-database
  namespace: geocoding
spec:
  imageName: ghcr.io/cloudnative-pg/postgis:16
  enableSuperuserAccess: true
  superuserSecret:
    name: geocoding-database-superuser
  bootstrap:
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION postgis;
        - CREATE EXTENSION postgis_topology;
        - CREATE EXTENSION fuzzystrmatch;
        - CREATE EXTENSION postgis_tiger_geocoder;
  postgresql:
    parameters:
      shared_buffers: "2GB"
      work_mem: "50MB"
      maintenance_work_mem: "10GB"
      autovacuum_work_mem: "2GB"
      effective_cache_size: "24GB"
      synchronous_commit: "off"
      checkpoint_timeout: "10min"
      max_wal_senders: "0"
      max_wal_size: "1GB"
      checkpoint_completion_target: "0.9"
      random_page_cost: "1.0"
  storage:
    size: 1250Gi
    storageClass: zfs
