apiVersion: v1
kind: Service
metadata:
  name: geocoding-database-nodeport
  namespace: geocoding
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: geocoding-database
    role: primary
  ports:
    - port: 5432
      nodePort: 30636

