apiVersion: v1
kind: Secret
metadata:
  name: victoriametrics-backup-secret
  namespace: monitoring
type: Opaque
stringData:
  RESTIC_REPOSITORY: "${api_endpoint}/${bucket_name}"
  RESTIC_PASSWORD: "${restic_secret}"
  AWS_ACCESS_KEY_ID: "${id}"
  AWS_SECRET_ACCESS_KEY: "${secret}"
