apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1p-kubernetes
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.secrets.svc.cluster.local:8080
      vaults:
        Kubernetes: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-api
            key: token
            namespace: secrets
