apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: 1p-tf-prod
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.secrets.svc.cluster.local:8080
      vaults:
        tf_prod: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-api
            key: token
            namespace: secrets
