apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app oauth2-proxy-secrets
  namespace: flux-system
spec:
  targetNamespace: authentication
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/apps/authentication/oauth2-proxy/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app oauth2-proxy
  namespace: flux-system
spec:
  targetNamespace: authentication
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: oauth2-proxy-secrets
  path: ./kubernetes/apps/authentication/oauth2-proxy/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
