apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-bot-db-backup-bucket
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-tf
  refreshInterval: "20s"
  data:
    - secretKey: bucket_name
      remoteRef:
        key: DISCORD_BOT_DB_BACKUP_BUCKET
        property: bucket_name
    - secretKey: api_endpoint
      remoteRef:
        key: DISCORD_BOT_DB_BACKUP_BUCKET
        property: endpoint
