apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-bot-db-backup-secret
  namespace: tools
  labels:
    cnpg.io/reload: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-tf
  refreshInterval: "20s"
  data:
    - secretKey: id
      remoteRef:
        key: DISCORD_BOT_DB_BACKUP_BUCKET
        property: access_key_id
    - secretKey: secret
      remoteRef:
        key: DISCORD_BOT_DB_BACKUP_BUCKET
        property: secret_access_key
