apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app outline-dev-secrets
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/apps/tools/outline-dev/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app outline-dev
  namespace: flux-system
spec:
  targetNamespace: outline-dev
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: outline-dev-secrets
  path: ./kubernetes/apps/tools/outline-dev/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: outline-dev-database-backup-bucket
