---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    controller:
      service:
        type: ClusterIP
      publishService:
        enabled: false
      hostPort:
        enabled: true
      ingressClassResource:
        default: true
      config:
        allow-snippet-annotations: true
        annotations-risk-level: Critical
      metrics:
        enabled: false
      updateStrategy:
        type: Restart
      resources:
        requests:
          cpu: 10m
          memory: 250Mi
