apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-prod-oauth-clientid
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-tf
  refreshInterval: "20s"
  data:
    - secretKey: GRAFANA_OAUTH_CLIENT_ID
      remoteRef:
        key: ZITADEL_OAUTH_CLIENT_ID_GRAFANA_MONITORING_PROD
