apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app1 victoria-metrics
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app1
  dependsOn:
    - name: grafana-operator
  path: ./kubernetes/apps/monitoring/victoria-metrics/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app2 cf-workers-metrics-ingress
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app2
  dependsOn:
    - name: victoria-metrics
  path: ./kubernetes/apps/monitoring/victoria-metrics/ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
