---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-snapshot-controller
  namespace: flux-system
spec:
  path: ./kubernetes/apps/infrastructure/storage/snapshot-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: snapshot-controller
      namespace: storage
  interval: 30m
  retryInterval: 1m
  timeout: 3m
