apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: tools
  labels:
    app: discord-bot
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: discord-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: discord-bot
        podbump.bo0tzz.me/enabled: "true"
    spec:
      containers:
        - name: discord-bot
          image: ghcr.io/immich-app/discord-bot:main
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: discord-bot
