---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zitadel-secrets
  namespace: flux-system
spec:
  targetNamespace: authentication
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/apps/authentication/zitadel/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zitadel-database
  namespace: flux-system
spec:
  targetNamespace: authentication
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: database-cloudnative-pg
  path: ./kubernetes/apps/authentication/zitadel/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zitadel
  namespace: flux-system
spec:
  targetNamespace: authentication
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: zitadel-secrets
    - name: zitadel-database
  path: ./kubernetes/apps/authentication/zitadel/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
