apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-volsync-repo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${VOLSYNC_SECRET_STORE}
  refreshInterval: "20s"
  target:
    template:
      engineVersion: v2
      data:
        RESTIC_PASSWORD: "{{ .restic_password }}"
        RESTIC_REPOSITORY: "s3:{{ .endpoint }}/{{ .bucket_name }}"
        AWS_ACCESS_KEY_ID: "{{ .access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_access_key }}"
  data:
    - secretKey: restic_password
      remoteRef:
        key: ${VOLSYNC_RESTIC_PASSWORD_SECRET}
    - secretKey: access_key_id
      remoteRef:
        key: ${VOLSYNC_BUCKET_SECRET}
        property: access_key_id
    - secretKey: secret_access_key
      remoteRef:
        key: ${VOLSYNC_BUCKET_SECRET}
        property: secret_access_key
    - secretKey: bucket_name
      remoteRef:
        key: ${VOLSYNC_BUCKET_SECRET}
        property: bucket_name
    - secretKey: endpoint
      remoteRef:
        key: ${VOLSYNC_BUCKET_SECRET}
        property: endpoint
