---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app preview-immich-release
  namespace: flux-system
spec:
  targetNamespace: preview
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./templates/kubernetes/immich-preview
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      NAME: preview-immich-release
      HOST: release-preview.internal.immich.cloud
      TAG: v1.124.2
