apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: cf-workers-metrics-ingress
spec:
  userSelector: {}
  userNamespaceSelector: {}
  selectAllByDefault: true
  ingress:
    tlsSecretName: cf-workers-metrics-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    class_name: nginx
    tlsHosts:
      - cf-workers.monitoring.immich.cloud
