apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vmetrics-write-token
  namespace: monitoring
spec:
  itemPath: "vaults/Kubernetes/items/vmetrics_write_token"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: write
  namespace: monitoring
  labels:
    vm-user: "write"
spec:
  tokenRef:
    name: vmetrics-write-token
    key: token
  targetRefs:
    - crd:
        kind: VMSingle
        name: vmetrics
        namespace: monitoring
      paths: ["/write"]
