apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-role-sync
  namespace: tools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-tf
  refreshInterval: "20s"
  data:
    - secretKey: OUTLINE_API_TOKEN
      remoteRef:
        key: OUTLINE_ROLE_SYNC_OUTLINE_API_TOKEN
    - secretKey: OUTLINE_WEBHOOK_SECRET
      remoteRef:
        key: OUTLINE_ROLE_SYNC_WEBHOOK_SECRET
    - secretKey: ZITADEL_SERVICE_ACCOUNT_TOKEN
      remoteRef:
        key: OUTLINE_ROLE_SYNC_ZITADEL_TOKEN
    - secretKey: ZITADEL_OUTLINE_PROJECT_ID
      remoteRef:
        key: OUTLINE_ROLE_SYNC_ZITADEL_PROJECT_ID
