name: 'Use Mise'
description: 'Use Mise with a pinned version'
inputs:
  github_token:
    description: 'Github token to use'
    required: true
  working_directory:
    required: false
    description: 'The directory that mise runs in'
runs:
  using: 'composite'
  steps:
    - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      with:
        github_token: ${{ inputs.github_token }}
        working_directory: ${{ inputs.working_directory }}
        cache_key_prefix: ${{ inputs.working_directory }}
        install_args: "--locked"
        version: 2026.8.14
