name: 'Use Mise'
description: 'Use Mise with a pinned version'
inputs:
  github_token:
    description: 'Github token to use'
    required: true
  working_directory:
    required: false
    description: 'The directory that mise runs in'
runs:
  using: 'composite'
  steps:
    - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      with:
        github_token: ${{ inputs.github_token }}
        working_directory: ${{ inputs.working_directory }}
        install_args: "--locked"
        version: 2026.6.10
