apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${NAME}
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:14.12-v0.3.0
  enableSuperuserAccess: true

  postgresql:
    shared_preload_libraries:
      - "vectors.so"

  storage:
    size: 10Gi
    storageClass: zfs
  backup:
    volumeSnapshot:
      className: zfs
