---
name: "Flux Diff"

on:
  pull_request:
    paths: ["kubernetes/**", "templates/kubernetes/**", ".github/workflows/flux-diff.yml"]

jobs:
  flux-diff:
    name: Flux Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Setup flate
        uses: home-operations/flate/action@0fc37fae10cf3c265294f6adebc6d6c100c74ea5 # v0.4.10
        with:
          base: "origin/${{ github.event.pull_request.base.ref }}"
          cache: true

      - name: Diff Resources
        id: diff
        run: |
          flate diff all --path ./kubernetes --allow-missing-secrets -o github > diff.txt
          {
            echo 'diff<<DIFF_EOF'
            cat diff.txt
            echo 'DIFF_EOF'
          } >> "${GITHUB_OUTPUT}"

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add comment
        uses: immich-app/devtools/actions/sticky-comment@0135acd12ad9f3369b94a2aa3c0ae8c835a4e926 # sticky-comment-action-v1.0.0
        with:
          id: "flux-diff"
          body: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
