---
name: "Flux Diff"

on:
  pull_request:
    paths: ["kubernetes/**", "templates/kubernetes/**", ".github/workflows/flux-diff.yml"]

jobs:
  flux-diff:
    name: Flux Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: write
    strategy:
      matrix:
        resource: ["helmrelease", "kustomization"]
    steps:
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@871be9b40d53627786d3a3835a3ddba1e3234bd2 # v2.8.3

      - name: Diff Resources
        uses: allenporter/flux-local/action/diff@d4ebcae7ae08c8c8b8b7c1f515cf86759f9ca950 # 8.1.0
        id: diff
        with:
          path: "./kubernetes"
          live-branch: "${{ github.event.pull_request.base.ref }}"
          resource: "${{ matrix.resource }}"
          skip-crds: "false"

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add comment
        uses: mshick/add-pr-comment@64b8e914979889d746c99dea15a76e77ef64580a # v3.10.0
        with:
          message-id: "${{ github.event.pull_request.number }}/${{ matrix.path }}/${{ matrix.resource }}"
          message-failure: Diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
