---
name: "Flux Diff"

on:
  pull_request:
    paths: ["kubernetes/**", "templates/kubernetes/**", ".github/workflows/flux-diff.yml"]

jobs:
  flux-diff:
    name: Flux Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: write
    strategy:
      matrix:
        resource: ["helmrelease", "kustomization"]
    steps:
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@1fd61a06264d71cf445ed55c4f14d401d26a1c64 # v2.8.8

      - name: Diff Resources
        uses: allenporter/flux-local/action/diff@88f56a2113aeda1551111d446734e9f4a4bee7d4 # 8.3.0
        id: diff
        with:
          path: "./kubernetes"
          live-branch: "${{ github.event.pull_request.base.ref }}"
          resource: "${{ matrix.resource }}"
          skip-crds: "false"

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add comment
        uses: immich-app/devtools/actions/sticky-comment@0135acd12ad9f3369b94a2aa3c0ae8c835a4e926 # sticky-comment-action-v1.0.0
        with:
          id: "flux-diff/${{ matrix.path }}/${{ matrix.resource }}"
          body: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
