name: Release Please

on:
  workflow_dispatch: # For manual runs
  release: # To update release PRs when one is merged
    types: [published]
  pull_request: # To handle the release label being removed
    types: [unlabeled]
  push: # Standard workflow
    branches:
      - main

concurrency: release-please

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: ${{ secrets.PUSH_O_MATIC_APP_ID }}
          private-key: ${{ secrets.PUSH_O_MATIC_APP_KEY }}

      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
