name: Release Please

on:
  workflow_dispatch: # For manual runs
  release: # To update release PRs when one is merged
    types: [published]
  pull_request: # To handle the release label being removed
    types: [unlabeled]
  push: # Standard workflow
    branches:
      - main

concurrency: release-please

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.PUSH_O_MATIC_APP_ID }}
          private-key: ${{ secrets.PUSH_O_MATIC_APP_KEY }}

      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
