name: PR Conventional Commit Validation

on:
  workflow_call:

permissions: {}

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # Potentially replace with https://github.com/amannn/action-semantic-pull-request
      - name: PR Conventional Commit Validation
        uses: ytanikin/PRConventionalCommits@b628c5a234cc32513014b7bfdd1e47b532124d98 # 1.3.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          add_label: 'false'
