apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tf-state-storage
  namespace: terraform
spec:
  imageName: ghcr.io/cnpg-io/postgresql:15.13
  
  bootstrap:
    recovery:
      backup:
        name: tf-state-daily-backup-20250605000000
      recoveryTarget:
        targetTime: "2025-05-06 12:19:00.00000+00"

  storage:
    size: 10Gi
    storageClass: zfs

  backup:
    retentionPolicy: "14d"
    barmanObjectStore:
      destinationPath: s3://${bucket_name}
      serverName: tf-state-storage-2
      endpointURL: ${api_endpoint}
      wal:
        compression: bzip2
        maxParallel: 8
      s3Credentials:
        accessKeyId:
          name: tf-state-backup-secret
          key: id
        secretAccessKey:
          name: tf-state-backup-secret
          key: secret
