apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tf-state-storage
  namespace: terraform
spec:
  bootstrap:
    initdb:
      database: tf_state
      owner: terraform
      secret:
        name: tf-state-storage-user
  storage:
    size: 10Gi
    storageClass: zfs

  backup:
    retentionPolicy: "14d"
    barmanObjectStore:
      destinationPath: s3://${bucket-name}
      endpointURL: ${api-endpoint}
      wal:
        compression: bzip2
      s3Credentials:
        accessKeyId:
          name: tf-state-backup-secret
          key: id
        secretAccessKey:
          name: tf-state-backup-secret
          key: secret
